Fix specifier with scoped rootName
glimmerjs/glimmer-di pull request #46
Opened 2018-06-20 00:18 UTC by gossi

Since npm supports scoped packages, e.g. `@glimmer/*` it wasn't supported with this library. Support is added. I'm wondering, wether this is complete and ready to merge or if I need to add/change something?

2018-06-20 00:44 UTC, dgeb requested changes
Looks good! Just a couple nits.

2018-06-20 00:44 UTC, dgeb commented on test/specifier-test.ts
> +test('#serializeSpecifier - serialier a Specificer object with a scoped rootName', function (assert) {
"serializes a specifier"

2018-06-20 00:44 UTC, dgeb commented on test/specifier-test.ts
> +test('#deserializeSpecifier - deserialiers a scoped rootName specifier string into a Serializer object', function (assert) {
"deserializes"

2018-06-20 01:26 UTC, dgeb approved these changes

2018-06-20 01:29 UTC, merged

2018-08-21 21:28 UTC, ef4 commented
I think this is still unreleased. I hit this issue while testing some MU stuff on ember canary.

2018-08-22 07:51 UTC, gossi commented
checky @dgeb ... he just rolled out a release. Thanks for this ❤️

2018-08-22 08:02 UTC, dgeb commented
@gossi @ef4 yeah, I _just_ published 0.2.1. Thanks for the reminder :)